Convert to es6 & Documentation
sagspot/sendIt pull request #1
Opened 2021-06-30 06:38 UTC by sagspot

2021-07-01 11:11 UTC, Nicanor008 requested changes
Nice stuff, just check on this improvements

2021-07-01 11:11 UTC, Nicanor008 commented on controllers/parcels.js
> +    res.status(500).send('Something went wrong');
Return something in try catch
```suggestion
  try {
    const receivedParcels = parcels.filter(
      (parcel) => parcel.toUser == req.user.email
    );
    return res.json({ sentParcels, receivedParcels });
  } catch (err) {
    return res.status(500).send('Something went wrong');
```

2021-07-01 11:11 UTC, Nicanor008 commented on controllers/parcels.js
> +import parcels from '../model/parcels.js';
Not sure why you adding the `.js`, it should automatically detect file type and import

2021-07-01 11:11 UTC, Nicanor008 commented on controllers/parcels.js
>    if (error) return res.status(400).send(error.details[0].message);
This is a bad pattern, prone to errors, and not scalable especially on data indexing change,
either just error only or details without the `[0]`

2021-07-01 11:11 UTC, Nicanor008 commented on controllers/parcels.js
>    if (error) return res.status(400).send(error.details[0].message);
same here

2021-07-01 11:11 UTC, Nicanor008 commented on controllers/users.js
> +      email: newUser.email,
How about you destructure this
```suggestion
     const { id, name, email } = newUser;
      id,
      name,
      email,
```

2021-07-02 07:33 UTC, sagspot commented on controllers/parcels.js
> +import parcels from '../model/parcels.js';
It doesn't, maybe that's the downside of using `{type: modules}`  in the package.json

2021-07-02 11:19 UTC, merged